/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js,jsx,ts,tsx}"],
  theme: {
    colors: {
      CC: "#3d6af2",
      translucent5: "rgba(255, 255, 255, 0.5)",
      translucent3: "rgba(255, 255, 255, 0.3)",
      translucent2: "rgba(255, 255, 255, 0.2)",
      translucent1: "rgba(255, 255, 255, 0.1)",
      transparent: "transparent",
      current: "currentColor",
      white: "#ffffff",
      purple: "#3f3cbb",
      midnight: "#121063",
      metal: "#565584",
      tahiti: "#3ab7bf",
      silver: "#ecebff",
      bubble: "#ff77e9",
      bermuda: "#78dcca",
      bbpurple: "#7F73FF",
      bbLpurple: "#F1EFFF",
      bborange: "#FFB800",
      bbyellow: "#FFEC8A",
      bbLyellow: "FFF6C9",
      bbgradientp: "#A66FFF",
      bbpink: "#6F75FF",
      BB: "#222222",
      bb44: "#666666",
      bb33: "#888888",
      bb22: "#BBBBBB",
      bb11: "#FBFBFB",
      red: "red",
      blue: "blue",
      beige: "beige",
      orange: "orange",
      gray: "Dgray",
      black: "black",
      D9: "#D9D9D9",
      HC: "D#F6F7FB",
      DD: "#8D8D8D",
      OO: "#606060",
      BGC: "#F6F7FB",
      EB: "#EBEBEB",
      C4: "#c4c4c4",
      KY: "#FAE100",
      F6: "#F6F7FB",

      DDD: "#DDDDDD",
    },
    fontFamily: {
      sans: ["Pretendard", "Pretendard Std Variable", "Pretendard Std"],
      custom: ["Pretendard"],
    },
    extend: {
      fontFamily: {
        sans: ["Pretendard", "Pretendard Std Variable", "Pretendard Std"],
        custom: ["Pretendard"],
      },
      fontSize: {
        p11: "11px",
        p12: "12px",
        p13: "13px",
        p14: "14px",
        p16: "16px",
        p18: "18px",
        p20: "20px",
        p24: "24px",
        p38: "38px",
        ha1: "0.5px",
      },
    },
  },
  plugins: [require("tailwind-scrollbar-hide")],
};
